name: CI/CD

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write   # needed to push to GHCR

jobs:
  lint:
    name: Lint (Node)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # Prefer a project lint script. If you don’t have one yet,
      # add it (see notes below).
      - name: Run lint
        run: |
          if npm run -s | grep -q "^  lint$"; then
            npm run lint
          else
            echo "No lint script found. Skipping. (Add an npm 'lint' script for real checks.)"
          fi

  build-and-push:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ github.event_name != 'pull_request' }}  # push images only on main/tags, not PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # (Optional) Log in to Docker Hub if secrets are provided
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generate tags/labels for GHCR + Docker Hub
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/node-hello
            ${{ secrets.DOCKERHUB_USERNAME && format('{0}/node-hello', secrets.DOCKERHUB_USERNAME) }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
